# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Alchemy Transmuter
tagline:          ''
description:      ''
url:              http://shopify.github.io/alchemy-transmuter-public
baseurl:          http://shopify.github.io/alchemy-transmuter-public
paginate:         5

author:
  name:           'Dale Hamel'
  url:            https://github.com/dalehamel

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/Shopify/alchemy-transmuter-public
